from datetime import datetime, timezone


def utc_now():
    """Get current UTC time as timezone-aware datetime."""
    return datetime.now(timezone.utc)


def format_topic(topic_name, summaries, format_type='markdown'):
    """Format topic summaries as blog post.
    
    Args:
        topic_name: Name of the topic
        summaries: List of summary dicts with 'title', 'summary', 'link'
        format_type: 'markdown' (default), 'jekyll', or 'hugo'
    
    Returns:
        Formatted blog post as string
    """
    now = utc_now()
    date_str = now.strftime('%Y-%m-%d')
    datetime_str = now.isoformat()
    
    # Generate front matter for static site generators
    if format_type == 'jekyll':
        header = f"""---
layout: post
title: "{topic_name} — Automated Curation"
date: {datetime_str}
categories: news {topic_name.lower().replace(' ', '-')}
tags: automated curated
---

"""
    elif format_type == 'hugo':
        header = f"""---
title: "{topic_name} — Automated Curation"
date: {datetime_str}
draft: false
categories: ["news", "{topic_name}"]
tags: ["automated", "curated"]
---

"""
    else:
        # Plain markdown
        header = f"# {topic_name} — Automated Curation ({date_str})\n\n"
    
    # Build body
    body = []
    if summaries:
        for idx, s in enumerate(summaries, start=1):
            title = s.get('title', 'Untitled')
            summary = s.get('summary', '')
            link = s.get('link', '')
            
            body.append(f"## {idx}. {title}\n\n")
            
            if summary:
                body.append(f"{summary}\n\n")
            
            if link:
                body.append(f"[Read original article →]({link})\n\n")
            
            body.append("---\n\n")
    else:
        body.append("*No articles available for this topic at this time.*\n\n")
    
    footer = f"\n*Generated by [NewsGenerator](https://github.com/vishc0/NewsGenerator) on {date_str}*\n"
    
    return header + ''.join(body) + footer
