from datetime import datetime


def format_topic(topic_name, summaries):
    now = datetime.utcnow().isoformat()
    header = f"# {topic_name} — Automated Curation ({now})\n\n"
    body = []
    for s in summaries:
        body.append(f"## {s.get('title')}\n\n")
        body.append(f"{s.get('summary')}\n\n")
        body.append(f"[Read original]({s.get('link')})\n\n---\n\n")

    footer = "\n*Generated by NewsGenerator*\n"
    return header + ''.join(body) + footer
